"""
Evidence Formatter

Formats evidence for presentation in Azure DevOps comments and reports.
"""

import logging
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from .evidence_collector import EvidenceCollector, EvidenceItem, EvidenceCategory

logger = logging.getLogger(__name__)


class ADOCommentFormat(Enum):
    """Format types for ADO comments."""

    PLAIN_TEXT = "plain_text"
    MARKDOWN = "markdown"
    HTML = "html"


class EvidenceFormatter:
    """
    Formats evidence for various output formats.

    Creates formatted reports and comments for Azure DevOps integration.
    """

    def __init__(self, work_item_id: str):
        """
        Initialize evidence formatter.

        Args:
            work_item_id: The work item ID
        """
        self.work_item_id = work_item_id
        self.logger = logging.getLogger(f"{__name__}.{self.__class__.__name__}")

    def format_stage_comment(
        self,
        stage: str,
        status: str,
        duration_seconds: float,
        evidence_items: List[EvidenceItem],
        metrics: Optional[Dict[str, Any]] = None,
        format_type: ADOCommentFormat = ADOCommentFormat.MARKDOWN,
    ) -> str:
        """
        Format a comment for a workflow stage.

        Args:
            stage: Stage name
            status: Stage status (passed/failed)
            duration_seconds: Stage duration
            evidence_items: Evidence items from stage
            metrics: Optional metrics dictionary
            format_type: Output format

        Returns:
            Formatted comment string
        """
        if format_type == ADOCommentFormat.MARKDOWN:
            return self._format_stage_comment_markdown(
                stage, status, duration_seconds, evidence_items, metrics
            )
        elif format_type == ADOCommentFormat.HTML:
            return self._format_stage_comment_html(
                stage, status, duration_seconds, evidence_items, metrics
            )
        else:
            return self._format_stage_comment_plain(
                stage, status, duration_seconds, evidence_items, metrics
            )

    def _format_stage_comment_markdown(
        self,
        stage: str,
        status: str,
        duration_seconds: float,
        evidence_items: List[EvidenceItem],
        metrics: Optional[Dict[str, Any]],
    ) -> str:
        """Format stage comment as markdown."""
        status_icon = "✅" if status == "passed" else "❌"

        comment = f"""## {status_icon} Stage: {stage.replace('_', ' ').title()}

**Status:** {status.upper()}
**Duration:** {duration_seconds:.1f}s
**Timestamp:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

"""

        # Add metrics if available
        if metrics:
            comment += "### Metrics\n\n"
            for key, value in metrics.items():
                comment += f"- **{key.replace('_', ' ').title()}:** {value}\n"
            comment += "\n"

        # Add evidence
        if evidence_items:
            comment += f"### Evidence ({len(evidence_items)} files)\n\n"

            # Group by category
            by_category = {}
            for item in evidence_items:
                cat = item.category.value
                if cat not in by_category:
                    by_category[cat] = []
                by_category[cat].append(item)

            for category, items in by_category.items():
                comment += f"**{category.title()}:**\n"
                for item in items:
                    comment += f"- `{item.filename}`"
                    if item.description:
                        comment += f" - {item.description}"
                    comment += "\n"
                comment += "\n"

        comment += "---\n*Generated by AI-SDLC Workflow Orchestrator*"

        return comment

    def _format_stage_comment_html(
        self,
        stage: str,
        status: str,
        duration_seconds: float,
        evidence_items: List[EvidenceItem],
        metrics: Optional[Dict[str, Any]],
    ) -> str:
        """Format stage comment as HTML."""
        status_icon = "✅" if status == "passed" else "❌"
        status_color = "#4CAF50" if status == "passed" else "#F44336"

        html = f"""
<div style="border: 1px solid #ddd; border-radius: 5px; padding: 15px; margin: 10px 0; background: #f9f9f9;">
    <h3 style="color: {status_color};">{status_icon} {stage.replace('_', ' ').title()}</h3>

    <table style="width: 100%; margin: 10px 0;">
        <tr>
            <td><strong>Status:</strong></td>
            <td style="color: {status_color};">{status.upper()}</td>
        </tr>
        <tr>
            <td><strong>Duration:</strong></td>
            <td>{duration_seconds:.1f}s</td>
        </tr>
        <tr>
            <td><strong>Timestamp:</strong></td>
            <td>{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</td>
        </tr>
    </table>
"""

        # Add metrics
        if metrics:
            html += "<h4>Metrics</h4><ul>"
            for key, value in metrics.items():
                html += f"<li><strong>{key.replace('_', ' ').title()}:</strong> {value}</li>"
            html += "</ul>"

        # Add evidence
        if evidence_items:
            html += f"<h4>Evidence ({len(evidence_items)} files)</h4><ul>"
            for item in evidence_items:
                html += f"<li><code>{item.filename}</code>"
                if item.description:
                    html += f" - {item.description}"
                html += "</li>"
            html += "</ul>"

        html += """
    <p style="font-size: 0.9em; color: #666; margin-top: 15px;">
        <em>Generated by AI-SDLC Workflow Orchestrator</em>
    </p>
</div>
"""

        return html

    def _format_stage_comment_plain(
        self,
        stage: str,
        status: str,
        duration_seconds: float,
        evidence_items: List[EvidenceItem],
        metrics: Optional[Dict[str, Any]],
    ) -> str:
        """Format stage comment as plain text."""
        status_icon = "[PASS]" if status == "passed" else "[FAIL]"

        lines = [
            f"{status_icon} Stage: {stage.replace('_', ' ').title()}",
            "",
            f"Status: {status.upper()}",
            f"Duration: {duration_seconds:.1f}s",
            f"Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",
        ]

        # Add metrics
        if metrics:
            lines.append("Metrics:")
            for key, value in metrics.items():
                lines.append(f"  - {key.replace('_', ' ').title()}: {value}")
            lines.append("")

        # Add evidence
        if evidence_items:
            lines.append(f"Evidence ({len(evidence_items)} files):")
            for item in evidence_items:
                desc = f" - {item.description}" if item.description else ""
                lines.append(f"  - {item.filename}{desc}")
            lines.append("")

        lines.append("---")
        lines.append("Generated by AI-SDLC Workflow Orchestrator")

        return "\n".join(lines)

    def format_workflow_summary(
        self,
        collector: EvidenceCollector,
        stage_results: Dict[str, Any],
        format_type: ADOCommentFormat = ADOCommentFormat.MARKDOWN,
    ) -> str:
        """
        Format complete workflow summary.

        Args:
            collector: Evidence collector with all items
            stage_results: Results from all stages
            format_type: Output format

        Returns:
            Formatted summary string
        """
        if format_type == ADOCommentFormat.MARKDOWN:
            return self._format_workflow_summary_markdown(collector, stage_results)
        elif format_type == ADOCommentFormat.HTML:
            return self._format_workflow_summary_html(collector, stage_results)
        else:
            return self._format_workflow_summary_plain(collector, stage_results)

    def _format_workflow_summary_markdown(
        self,
        collector: EvidenceCollector,
        stage_results: Dict[str, Any],
    ) -> str:
        """Format workflow summary as markdown."""
        summary = collector.get_summary()

        # Count passed/failed stages
        total_stages = len(stage_results)
        passed_stages = sum(
            1 for r in stage_results.values() if r.get("status") == "passed"
        )
        failed_stages = total_stages - passed_stages

        md = f"""# 🤖 AI-SDLC Workflow Complete

**Work Item:** {self.work_item_id}
**Completed:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Status:** {'✅ SUCCESS' if failed_stages == 0 else '⚠️ PARTIAL SUCCESS' if passed_stages > 0 else '❌ FAILED'}

---

## Summary

- **Total Stages:** {total_stages}
- **Passed:** {passed_stages} ✅
- **Failed:** {failed_stages} ❌
- **Evidence Artifacts:** {summary['total_items']}
- **Screenshots:** {summary['screenshots_count']}

---

## Stage Results

"""

        for stage, result in stage_results.items():
            status = result.get("status", "unknown")
            icon = "✅" if status == "passed" else "❌"
            duration = result.get("duration_seconds", 0)
            md += f"- {icon} **{stage.replace('_', ' ').title()}** - {duration:.1f}s\n"

        md += f"""

---

## Evidence Artifacts

"""

        # Group evidence by category
        for category in EvidenceCategory:
            items = collector.get_evidence_by_category(category)
            if items:
                md += f"### {category.value.title()} ({len(items)})\n\n"
                for item in items[:5]:  # Show first 5
                    md += f"- `{item.filename}` (from {item.stage})\n"
                if len(items) > 5:
                    md += f"- ... and {len(items) - 5} more\n"
                md += "\n"

        md += """---

*Generated by AI-SDLC Workflow Orchestrator*
*🚀 Powered by Claude Code*
"""

        return md

    def _format_workflow_summary_html(
        self,
        collector: EvidenceCollector,
        stage_results: Dict[str, Any],
    ) -> str:
        """Format workflow summary as HTML."""
        summary = collector.get_summary()

        total_stages = len(stage_results)
        passed_stages = sum(
            1 for r in stage_results.values() if r.get("status") == "passed"
        )
        failed_stages = total_stages - passed_stages

        status_color = "#4CAF50" if failed_stages == 0 else "#FF9800"

        html = f"""
<div style="border: 2px solid {status_color}; border-radius: 10px; padding: 20px; background: #f9f9f9;">
    <h2 style="color: {status_color};">🤖 AI-SDLC Workflow Complete</h2>

    <table style="width: 100%; margin: 15px 0;">
        <tr>
            <td><strong>Work Item:</strong></td>
            <td>{self.work_item_id}</td>
        </tr>
        <tr>
            <td><strong>Completed:</strong></td>
            <td>{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</td>
        </tr>
        <tr>
            <td><strong>Status:</strong></td>
            <td style="color: {status_color};">{'✅ SUCCESS' if failed_stages == 0 else '⚠️ PARTIAL' if passed_stages > 0 else '❌ FAILED'}</td>
        </tr>
    </table>

    <h3>Summary</h3>
    <ul>
        <li><strong>Total Stages:</strong> {total_stages}</li>
        <li><strong>Passed:</strong> {passed_stages} ✅</li>
        <li><strong>Failed:</strong> {failed_stages} ❌</li>
        <li><strong>Evidence Artifacts:</strong> {summary['total_items']}</li>
        <li><strong>Screenshots:</strong> {summary['screenshots_count']}</li>
    </ul>

    <h3>Stage Results</h3>
    <table style="width: 100%; border-collapse: collapse;">
        <thead>
            <tr style="background: #e0e0e0;">
                <th style="padding: 8px; text-align: left;">Stage</th>
                <th style="padding: 8px; text-align: left;">Status</th>
                <th style="padding: 8px; text-align: left;">Duration</th>
            </tr>
        </thead>
        <tbody>
"""

        for stage, result in stage_results.items():
            status = result.get("status", "unknown")
            icon = "✅" if status == "passed" else "❌"
            duration = result.get("duration_seconds", 0)
            html += f"""
            <tr>
                <td style="padding: 8px;">{stage.replace('_', ' ').title()}</td>
                <td style="padding: 8px;">{icon} {status.upper()}</td>
                <td style="padding: 8px;">{duration:.1f}s</td>
            </tr>
"""

        html += """
        </tbody>
    </table>

    <p style="margin-top: 20px; font-size: 0.9em; color: #666;">
        <em>Generated by AI-SDLC Workflow Orchestrator • 🚀 Powered by Claude Code</em>
    </p>
</div>
"""

        return html

    def _format_workflow_summary_plain(
        self,
        collector: EvidenceCollector,
        stage_results: Dict[str, Any],
    ) -> str:
        """Format workflow summary as plain text."""
        summary = collector.get_summary()

        total_stages = len(stage_results)
        passed_stages = sum(
            1 for r in stage_results.values() if r.get("status") == "passed"
        )
        failed_stages = total_stages - passed_stages

        lines = [
            "AI-SDLC Workflow Complete",
            "=" * 50,
            "",
            f"Work Item: {self.work_item_id}",
            f"Completed: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            f"Status: {'SUCCESS' if failed_stages == 0 else 'PARTIAL' if passed_stages > 0 else 'FAILED'}",
            "",
            "Summary:",
            f"  Total Stages: {total_stages}",
            f"  Passed: {passed_stages}",
            f"  Failed: {failed_stages}",
            f"  Evidence Artifacts: {summary['total_items']}",
            f"  Screenshots: {summary['screenshots_count']}",
            "",
            "Stage Results:",
        ]

        for stage, result in stage_results.items():
            status = result.get("status", "unknown")
            icon = "[PASS]" if status == "passed" else "[FAIL]"
            duration = result.get("duration_seconds", 0)
            lines.append(f"  {icon} {stage.replace('_', ' ').title()} - {duration:.1f}s")

        lines.extend([
            "",
            "=" * 50,
            "Generated by AI-SDLC Workflow Orchestrator",
        ])

        return "\n".join(lines)
