"""
Unit tests for EvidenceFormatter.
"""

import pytest
from ai_sdlc.evidence import (
    EvidenceFormatter,
    ADOCommentFormat,
    EvidenceCollector,
    EvidenceCategory,
)


@pytest.mark.unit
class TestEvidenceFormatter:
    """Test suite for EvidenceFormatter."""

    @pytest.fixture
    def formatter(self, work_item_id):
        """Create EvidenceFormatter instance."""
        return EvidenceFormatter(work_item_id=work_item_id)

    def test_initialization(self, formatter, work_item_id):
        """Test formatter initializes correctly."""
        assert formatter.work_item_id == work_item_id

    def test_format_stage_comment_markdown(
        self, formatter, sample_evidence_items
    ):
        """Test formatting stage comment as Markdown."""
        comment = formatter.format_stage_comment(
            stage="unit_testing",
            status="passed",
            duration_seconds=12.5,
            evidence_items=sample_evidence_items,
            metrics={"coverage": 85.5, "tests_passed": 42},
            format_type=ADOCommentFormat.MARKDOWN,
        )

        # Verify Markdown formatting
        assert "## ✅ Stage: Unit Testing" in comment
        assert "**Status:** PASSED" in comment
        assert "**Duration:** 12.5s" in comment
        assert "### Metrics" in comment
        assert "Coverage" in comment
        assert "85.5" in comment
        assert "### Evidence" in comment
        assert "Generated by AI-SDLC Workflow Orchestrator" in comment

    def test_format_stage_comment_html(self, formatter, sample_evidence_items):
        """Test formatting stage comment as HTML."""
        comment = formatter.format_stage_comment(
            stage="unit_testing",
            status="passed",
            duration_seconds=12.5,
            evidence_items=sample_evidence_items,
            metrics={"coverage": 85.5},
            format_type=ADOCommentFormat.HTML,
        )

        # Verify HTML formatting
        assert "<div" in comment
        assert "<h3" in comment
        assert "<table" in comment
        assert "✅" in comment
        assert "PASSED" in comment
        assert "12.5s" in comment
        assert "Generated by AI-SDLC Workflow Orchestrator" in comment

    def test_format_stage_comment_plain_text(
        self, formatter, sample_evidence_items
    ):
        """Test formatting stage comment as plain text."""
        comment = formatter.format_stage_comment(
            stage="unit_testing",
            status="passed",
            duration_seconds=12.5,
            evidence_items=sample_evidence_items,
            metrics={"coverage": 85.5},
            format_type=ADOCommentFormat.PLAIN_TEXT,
        )

        # Verify plain text formatting
        assert "[PASS] Stage: Unit Testing" in comment
        assert "Status: PASSED" in comment
        assert "Duration: 12.5s" in comment
        assert "Metrics:" in comment
        assert "Evidence" in comment
        assert "Generated by AI-SDLC Workflow Orchestrator" in comment

    def test_format_stage_comment_failed_status(
        self, formatter, sample_evidence_items
    ):
        """Test formatting comment for failed stage."""
        comment = formatter.format_stage_comment(
            stage="unit_testing",
            status="failed",
            duration_seconds=5.0,
            evidence_items=sample_evidence_items,
            format_type=ADOCommentFormat.MARKDOWN,
        )

        assert "❌" in comment
        assert "FAILED" in comment

    def test_format_stage_comment_no_metrics(
        self, formatter, sample_evidence_items
    ):
        """Test formatting comment without metrics."""
        comment = formatter.format_stage_comment(
            stage="unit_testing",
            status="passed",
            duration_seconds=12.5,
            evidence_items=sample_evidence_items,
            metrics=None,
            format_type=ADOCommentFormat.MARKDOWN,
        )

        # Metrics section should not be present
        assert "### Metrics" not in comment

    def test_format_stage_comment_no_evidence(self, formatter):
        """Test formatting comment without evidence items."""
        comment = formatter.format_stage_comment(
            stage="unit_testing",
            status="passed",
            duration_seconds=12.5,
            evidence_items=[],
            format_type=ADOCommentFormat.MARKDOWN,
        )

        # Evidence section should be minimal or absent
        assert "## ✅ Stage: Unit Testing" in comment
        assert "**Status:** PASSED" in comment

    def test_format_workflow_summary_markdown(
        self, formatter, work_item_id, temp_dir, sample_stage_results
    ):
        """Test formatting workflow summary as Markdown."""
        # Create collector with evidence
        collector = EvidenceCollector(work_item_id, temp_dir)

        summary = formatter.format_workflow_summary(
            collector=collector,
            stage_results=sample_stage_results,
            format_type=ADOCommentFormat.MARKDOWN,
        )

        # Verify summary content
        assert "# 🤖 AI-SDLC Workflow Complete" in summary
        assert f"**Work Item:** {work_item_id}" in summary
        assert "## Summary" in summary
        assert "## Stage Results" in summary
        assert "planning" in summary.lower()
        assert "code_generation" in summary.lower()
        assert "Generated by AI-SDLC Workflow Orchestrator" in summary

    def test_format_workflow_summary_html(
        self, formatter, work_item_id, temp_dir, sample_stage_results
    ):
        """Test formatting workflow summary as HTML."""
        collector = EvidenceCollector(work_item_id, temp_dir)

        summary = formatter.format_workflow_summary(
            collector=collector,
            stage_results=sample_stage_results,
            format_type=ADOCommentFormat.HTML,
        )

        # Verify HTML formatting
        assert "<div" in summary
        assert "<h2" in summary
        assert "<table" in summary
        assert "AI-SDLC Workflow Complete" in summary
        assert work_item_id in summary

    def test_format_workflow_summary_plain(
        self, formatter, work_item_id, temp_dir, sample_stage_results
    ):
        """Test formatting workflow summary as plain text."""
        collector = EvidenceCollector(work_item_id, temp_dir)

        summary = formatter.format_workflow_summary(
            collector=collector,
            stage_results=sample_stage_results,
            format_type=ADOCommentFormat.PLAIN_TEXT,
        )

        # Verify plain text formatting
        assert "AI-SDLC Workflow Complete" in summary
        assert work_item_id in summary
        assert "Summary:" in summary
        assert "Stage Results:" in summary

    def test_format_workflow_summary_success_status(
        self, formatter, work_item_id, temp_dir
    ):
        """Test workflow summary with all stages passed."""
        collector = EvidenceCollector(work_item_id, temp_dir)
        stage_results = {
            "planning": {"status": "passed"},
            "code_generation": {"status": "passed"},
            "unit_testing": {"status": "passed"},
        }

        summary = formatter.format_workflow_summary(
            collector=collector,
            stage_results=stage_results,
            format_type=ADOCommentFormat.MARKDOWN,
        )

        assert "✅ SUCCESS" in summary

    def test_format_workflow_summary_partial_success(
        self, formatter, work_item_id, temp_dir
    ):
        """Test workflow summary with some stages failed."""
        collector = EvidenceCollector(work_item_id, temp_dir)
        stage_results = {
            "planning": {"status": "passed"},
            "code_generation": {"status": "failed"},
            "unit_testing": {"status": "passed"},
        }

        summary = formatter.format_workflow_summary(
            collector=collector,
            stage_results=stage_results,
            format_type=ADOCommentFormat.MARKDOWN,
        )

        assert "⚠️ PARTIAL SUCCESS" in summary

    def test_format_workflow_summary_all_failed(
        self, formatter, work_item_id, temp_dir
    ):
        """Test workflow summary with all stages failed."""
        collector = EvidenceCollector(work_item_id, temp_dir)
        stage_results = {
            "planning": {"status": "failed"},
            "code_generation": {"status": "failed"},
        }

        summary = formatter.format_workflow_summary(
            collector=collector,
            stage_results=stage_results,
            format_type=ADOCommentFormat.MARKDOWN,
        )

        assert "❌ FAILED" in summary

    def test_evidence_grouping_by_category(
        self, formatter, temp_dir, work_item_id
    ):
        """Test that evidence is grouped by category in comments."""
        from pathlib import Path

        collector = EvidenceCollector(work_item_id, temp_dir)

        # Add evidence of different categories
        for i in range(2):
            file_path = Path(temp_dir) / f"test_{i}.py"
            file_path.write_text("code")
            collector.add_evidence(
                str(file_path), EvidenceCategory.TEST, "unit_testing"
            )

        file_path = Path(temp_dir) / "report.html"
        file_path.write_text("report")
        collector.add_report(str(file_path), "unit_testing")

        evidence_items = collector.get_all_evidence()

        comment = formatter.format_stage_comment(
            stage="unit_testing",
            status="passed",
            duration_seconds=10.0,
            evidence_items=evidence_items,
            format_type=ADOCommentFormat.MARKDOWN,
        )

        # Verify categories are shown
        assert "Test:" in comment or "test" in comment.lower()
        assert "Report:" in comment or "report" in comment.lower()
